Run shfmt on script files

diff --git a/dl-distro b/dl-distro
--- a/dl-distro
+++ b/dl-distro
@@ -86,17 +86,33 @@ declare -A supported_distros=(
 	["Zorin OS"]="zorin"
 )
 
-msg() { printf "%b%s%b\n" "$bold" "$1" "$reset"; }
-warn() { printf >&2 "%b%bWARNING:%b %s%b\n" "$bold" "$yellow" "$nc" "$1" "$reset"; }
-error() { printf >&2 "%b%bERROR:%b %s%b\n" "$bold" "$red" "$nc" "$1" "$reset"; }
-die() { error "$1"; exit 1; }
+msg()
+{
+	printf "%b%s%b\n" "$bold" "$1" "$reset"
+}
+
+warn()
+{
+	printf >&2 "%b%bWARNING:%b %s%b\n" "$bold" "$yellow" "$nc" "$1" "$reset"
+}
+
+error()
+{
+	printf >&2 "%b%bERROR:%b %s%b\n" "$bold" "$red" "$nc" "$1" "$reset"
+}
+
+die()
+{
+	error "$1"
+	exit 1
+}
 
 dependency_check()
 {
 	missing_deps=()
 
 	for cmd in "$@"; do
-		command -v "$cmd" &> /dev/null || missing_deps+=("$cmd")
+		command -v "$cmd" &>/dev/null || missing_deps+=("$cmd")
 	done
 
 	if [[ "${#missing_deps[@]}" -gt 0 ]]; then
@@ -140,10 +156,10 @@ fetch_gpg_key()
 
 	gpg_key="$(jq -r ".gpg_keys.$1" "$json_file")"
 
-	if ! gpg --homedir "$gpg_dir" --list-keys "$gpg_key" &> /dev/null; then
+	if ! gpg --homedir "$gpg_dir" --list-keys "$gpg_key" &>/dev/null; then
 		msg "Fetching GPG key..."
 
-		if ! gpg --homedir "$gpg_dir" --keyserver "$gpg_keyserver" --recv-keys "$gpg_key" &> /dev/null; then
+		if ! gpg --homedir "$gpg_dir" --keyserver "$gpg_keyserver" --recv-keys "$gpg_key" &>/dev/null; then
 			die "Failed to fetch GPG key: ${red}$gpg_key"
 		fi
 	fi
@@ -153,7 +169,7 @@ verify_gpg_signature()
 {
 	[[ "$verification_enabled" == "false" ]] && return 0
 
-	if gpg --homedir "$gpg_dir" --verify "$@" &> /dev/null; then
+	if gpg --homedir "$gpg_dir" --verify "$@" &>/dev/null; then
 		msg "GPG verification: ${green}SUCCESS"
 	else
 		rm -f "$iso_file"
@@ -183,7 +199,7 @@ verify_minisign_signature()
 {
 	[[ "$verification_enabled" == "false" ]] && return 0
 
-	if minisign -Vp "$minisign_dir/$minisign_key" -x "$sig_file" -m "$sum_file" &> /dev/null; then
+	if minisign -Vp "$minisign_dir/$minisign_key" -x "$sig_file" -m "$sum_file" &>/dev/null; then
 		msg "Minisign verification: ${green}SUCCESS"
 	else
 		die "Minisign verification: ${red}FAILED"
@@ -227,7 +243,7 @@ verify_signify_signature()
 {
 	[[ "$verification_enabled" == "false" ]] && return 0
 
-	if "$signify_name" -Vp "$signify_dir/$signify_key" -x "$sig_file" -m "$sum_file" &> /dev/null; then
+	if "$signify_name" -Vp "$signify_dir/$signify_key" -x "$sig_file" -m "$sum_file" &>/dev/null; then
 		msg "Signify verification: ${green}SUCCESS"
 	else
 		die "Signify verification: ${red}FAILED"
@@ -236,7 +252,7 @@ verify_signify_signature()
 
 verify_checksum()
 {
-	if "$sum_algo" -c --ignore-missing "$sum_file" &> /dev/null; then
+	if "$sum_algo" -c --ignore-missing "$sum_file" &>/dev/null; then
 		msg "$sum_algo verification: ${green}SUCCESS"
 	else
 		rm -f "$iso_file"
@@ -335,12 +351,7 @@ download_alma()
 
 	manual_download
 	wget_spider "$url"/{"$iso_file","$sig_file","$sum_file"}
-
-	if [[ "$traverse_path" == *"${distro}_8"* ]]; then
-		fetch_gpg_key "${distro}_8"
-	else
-		fetch_gpg_key "${distro}_9"
-	fi
+	fetch_gpg_key "$distro"
 
 	if [[ "$traverse_path" == *"live"* ]]; then
 		wget_file "$url"/{"$sig_file","$sum_file"}
@@ -492,13 +503,13 @@ download_kali()
 {
 	if [[ "$traverse_path" == *"weekly"* ]]; then
 		html_content="$(wget -qO- "$url/")"
-		current_week_num="$(grep -o 'W[0-9]\+' <<< "$html_content" | sort -r | head -n 1 | cut -c2-)"
+		current_week_num="$(grep -o 'W[0-9]\+' <<<"$html_content" | sort -r | head -n 1 | cut -c2-)"
 		iso_file="${iso_file//\{current_week_num\}/$current_week_num}"
 
-		if ! grep -qF "$iso_file" <<< "$html_content"; then
+		if ! grep -qF "$iso_file" <<<"$html_content"; then
 			warn "No new ISO for week: ${yellow}$current_week_num"
 			warn "Downloading previous week."
-			(( prev_week_num=current_week_num-1 ))
+			((prev_week_num = current_week_num - 1))
 			iso_file="${iso_file//$current_week_num/$prev_week_num}"
 		fi
 	fi
@@ -528,8 +539,8 @@ download_nix()
 	manual_download
 	wget_spider "$url"/{"$iso_file","$sig_file","$sum_file"}
 	wget_file "$url"/{"$sum_file","$iso_file"}
-	printf "\n" >> "$sum_file"
-	read -r line < "$sum_file"
+	printf "\n" >>"$sum_file"
+	read -r line <"$sum_file"
 	new_iso_file="${line##* }"
 	mv "$iso_file" "$new_iso_file"
 	iso_file="$new_iso_file"
@@ -555,7 +566,7 @@ download_openbsd()
 	verify_signify_signature
 	wget_file "$url/$iso_file"
 	verify_checksum
-	IFS="." read -ra path_parts <<< "$traverse_path"
+	IFS="." read -ra path_parts <<<"$traverse_path"
 	architecture="${path_parts[3]}"
 	base_name="${iso_file%.*}"
 	ext="${iso_file##*.}"
@@ -569,7 +580,7 @@ download_opensuse()
 	fetch_gpg_key "$distro"
 	wget_file "$url"/{"$sig_file","$sum_file"}
 	verify_gpg_signature "$sig_file" "$sum_file"
-	read -r line < "$sum_file"
+	read -r line <"$sum_file"
 	iso_file="${line##* }"
 	wget_file "$url/$iso_file"
 	verify_checksum
@@ -762,9 +773,16 @@ generate_conf_file()
 
 		select gen_conf_choice in "Yes" "No"; do
 			case "$gen_conf_choice" in
-				"Yes") break ;;
-				"No") msg "Canceled."; return 0 ;;
-				*) error "Invalid option: ${red}$REPLY" ;;
+				"Yes")
+					break
+					;;
+				"No")
+					msg "Canceled."
+					return 0
+					;;
+				*)
+					error "Invalid option: ${red}$REPLY"
+					;;
 			esac
 		done
 	fi
@@ -777,7 +795,7 @@ generate_conf_file()
 		printf 'spider_mode_enabled="false"\n'
 		printf 'manual_download_enabled="false"\n'
 		printf 'gpg_keyserver="hkps://keyserver.ubuntu.com"\n'
-	} > "$conf_file"
+	} >"$conf_file"
 
 	msg "Made config file at: ${green}$conf_file"
 }
@@ -792,7 +810,7 @@ delete_gpg_key()
 		die "A GPG key ID is required."
 	fi
 
-	if gpg --homedir "$gpg_dir" --yes --batch --delete-keys "$gpg_key_id" &> /dev/null; then
+	if gpg --homedir "$gpg_dir" --yes --batch --delete-keys "$gpg_key_id" &>/dev/null; then
 		msg "GPG key deletion: ${green}SUCCESS"
 	else
 		die "GPG key deletion: ${red}FAILED"
@@ -809,7 +827,7 @@ import_gpg_key()
 		die "A path to a GPG key file is required."
 	fi
 
-	if gpg --homedir "$gpg_dir" --import "$gpg_key_file" &> /dev/null; then
+	if gpg --homedir "$gpg_dir" --import "$gpg_key_file" &>/dev/null; then
 		msg "GPG key import: ${green}SUCCESS"
 	else
 		die "GPG key import: ${red}FAILED"
@@ -820,7 +838,7 @@ list_gpg_keys()
 {
 	dependency_check "gpg"
 
-	list_keys_output="$(gpg --homedir "$gpg_dir" --list-keys 2> /dev/null)"
+	list_keys_output="$(gpg --homedir "$gpg_dir" --list-keys 2>/dev/null)"
 
 	if [[ -z "$list_keys_output" ]]; then
 		msg "No GPG keys saved."
@@ -933,7 +951,7 @@ traverse_json_file()
 {
 	traverse_path="$1"
 
-	if jq -e "$traverse_path.url" "$json_file" &> /dev/null; then
+	if jq -e "$traverse_path.url" "$json_file" &>/dev/null; then
 		start_download
 	fi
 
@@ -1014,7 +1032,7 @@ cli_mode()
 		fi
 	done
 
-	if type download_"$distro" &> /dev/null; then
+	if type download_"$distro" &>/dev/null; then
 		wait
 
 		traverse_json_file ".${json_query:-$distro}"
@@ -1027,11 +1045,17 @@ parse_opts()
 {
 	cli_mode=0
 
-	while [[ "$#" -gt 0 ]]; do
+	while (($#)); do
 		case "$1" in
-			-a|--auto-update) toggle_auto_update; exit 0 ;;
-			-c|--conf-file) generate_conf_file; exit 0 ;;
-			-d|--distro)
+			-a | --auto-update)
+				toggle_auto_update
+				exit 0
+				;;
+			-c | --conf-file)
+				generate_conf_file
+				exit 0
+				;;
+			-d | --distro)
 				if [[ -n "${2:-}" ]]; then
 					d_option_arg="$2"
 					cli_mode=1
@@ -1040,14 +1064,35 @@ parse_opts()
 					die "$1 requires a distro name or JSON query."
 				fi
 				;;
-			-D|--delete-key) delete_gpg_key "${2:-}"; exit 0 ;;
-			-h|--help) usage; exit 0 ;;
-			-i|--import-key) import_gpg_key "${2:-}"; exit 0 ;;
-			-l|--list-keys) list_gpg_keys; exit 0 ;;
-			-L|--list-distros) list_distros; exit 0 ;;
-			-m|--manual-download) manual_download_enabled="true"; shift 1 ;;
-			-n|--no-verify) verification_enabled="false"; shift 1 ;;
-			-p|--path)
+			-D | --delete-key)
+				delete_gpg_key "${2:-}"
+				exit 0
+				;;
+			-h | --help)
+				usage
+				exit 0
+				;;
+			-i | --import-key)
+				import_gpg_key "${2:-}"
+				exit 0
+				;;
+			-l | --list-keys)
+				list_gpg_keys
+				exit 0
+				;;
+			-L | --list-distros)
+				list_distros
+				exit 0
+				;;
+			-m | --manual-download)
+				manual_download_enabled="true"
+				shift 1
+				;;
+			-n | --no-verify)
+				verification_enabled="false"
+				shift 1
+				;;
+			-p | --path)
 				if [[ -n "${2:-}" ]]; then
 					default_download_dir="$2"
 					shift 2
@@ -1055,18 +1100,32 @@ parse_opts()
 					die "$1 requires a directory path."
 				fi
 				;;
-			-P|--purge-data) purge_all_data; exit 0 ;;
-			-s|--spider) spider_mode_enabled="true"; shift 1 ;;
-			-u|--update-json) update_json_file; shift 1 ;;
-			-V|--version) printf "%s\n" "$version"; exit 0 ;;
-			*) die "Invalid option: ${red}$1" ;;
+			-P | --purge-data)
+				purge_all_data
+				exit 0
+				;;
+			-s | --spider)
+				spider_mode_enabled="true"
+				shift 1
+				;;
+			-u | --update-json)
+				update_json_file
+				shift 1
+				;;
+			-V | --version)
+				printf "%s\n" "$version"
+				exit 0
+				;;
+			*)
+				die "Invalid option: ${red}$1"
+				;;
 		esac
 	done
 }
 
 main()
 {
-	[[ "$UID" -eq 0 ]] && die "Do not run as root."
+	((EUID == 0)) && die "Do not run as root."
 
 	dependency_check "jq" "wget"
 
@@ -1076,7 +1135,7 @@ main()
 	parse_opts "$@"
 
 	if [[ ! -f "$json_file" || "$auto_update_enabled" == "true" ]]; then
-		update_json_file > /dev/null &
+		update_json_file >/dev/null &
 	fi
 
 	mkdir -p "$default_download_dir"
