dl-distro: add print_messages for various fetches

diff --git a/dl-distro b/dl-distro
--- a/dl-distro
+++ b/dl-distro
@@ -20,12 +20,12 @@
 set -euo pipefail
 
 print_error_and_exit() {
-	printf "[dl-distro] Error: %s\n" "$1" >&2
+	printf "[dl-distro] ERROR: %s\n" "$1" >&2
 	exit 1
 }
 
 print_warning() {
-	printf "[dl-distro] Warning: %s\n" "$1" >&2
+	printf "[dl-distro] WARNING: %s\n" "$1" >&2
 }
 
 print_message() {
@@ -72,7 +72,7 @@ fetch_and_assign_values() {
 	fetch_json
 	keys=("$@")
 
-	jq_query="$(printf ".${distro}.%s, " "${keys[@]}")"
+	jq_query=".${distro} | $(printf ".%s, " "${keys[@]}")"
 	jq_query="${jq_query%, }"
 
 	readarray -t values < <(jq -r "$jq_query" "${json_file:-$fetched_json_file}")
@@ -106,6 +106,8 @@ fetch_json() {
 	done
 
 	fetched_json_file="$(mktemp)"
+
+	print_message "Fetching data.json from master branch."
 
 	for json_url in "${json_urls[@]}"; do
 		if wget -qc -O "$fetched_json_file" "$json_url"; then
@@ -145,8 +147,11 @@ fetch_verification_key() {
 			[[ ! -d "$gpg_dir" ]] && mkdir -p "$gpg_dir" && chmod 700 "$gpg_dir"
 
 			if ! gpg --homedir "$gpg_dir" --list-keys "$gpg_key" &> /dev/null; then
+
+				print_message "Fetching gpg key."
+
 				if ! gpg --homedir "$gpg_dir" --keyserver keyserver.ubuntu.com --recv-keys "$gpg_key" &> /dev/null; then
-					print_error_and_exit "Failed to fetch GPG key: $gpg_key"
+					print_error_and_exit "Failed to fetch gpg key: $gpg_key"
 				fi
 			fi
 			;;
@@ -159,6 +164,8 @@ fetch_verification_key() {
 
 			fetched_verification_key="$(mktemp)"
 
+			print_message "Fetching $verification_tool key."
+
 			if ! wget -qO- "$gpg_key" > "$fetched_verification_key"; then
 				print_error_and_exit "Failed to fetch $verification_tool key from: $gpg_key"
 			fi
@@ -166,7 +173,7 @@ fetch_verification_key() {
 	esac
 }
 
-find_signify_name(){
+find_signify_name() {
 	if [[ ! -f /etc/os-release ]]; then
 		print_error_and_exit "Cannot determine your distribution because /etc/os-release is missing."
 	fi
