fix colors
was forcing white text before.
now using default terminal color + bold, and coloring warnings
and errors.

diff --git a/dl-distro b/dl-distro
--- a/dl-distro
+++ b/dl-distro
@@ -41,13 +41,14 @@ verification_enabled="true"
 spider_mode_enabled="false"
 gpg_keyserver="hkps://keyserver.ubuntu.com"
 json_url="https://codeberg.org/bashuser30/dl-distro/raw/branch/master/data.json"
-green=$'\033[1;32m'
-red=$'\033[1;31m'
-yellow=$'\033[1;33m'
-bold=$'\033[1;37m'
-und=$'\033[1;4m'
-nc=$'\033[0m'
-PS3="${bold}>${nc} "
+green=$'\033[32m'
+red=$'\033[31m'
+yellow=$'\033[33m'
+bold=$'\033[1m'
+und=$'\033[4m'
+nc=$'\033[39m'
+reset=$'\033[0m'
+PS3="${bold}>${reset} "
 
 # shellcheck source=/dev/null
 [[ -f "$conf_file" ]] && source "$conf_file"
@@ -76,9 +77,9 @@ supported_distros=(["AlmaLinux OS"]="alma"
                    ["Void Linux"]="void"
                    ["Whonix"]="whonix")
 
-print_msg() { printf "%b%s%b\n" "$bold" "$1" "$nc"; }
-print_warn() { printf "%bWARNING: %b%s%b\n" "$yellow" "$bold" "$1" "$nc" >&2; }
-print_error() { printf "%bERROR: %b%s%b\n" "$red" "$bold" "$1" "$nc" >&2; }
+print_msg() { printf "%b%s%b\n" "$bold" "$1" "$reset"; }
+print_warn() { printf "%b%bWARNING:%b %s%b\n" "$bold" "$yellow" "$nc" "$1" "$reset" >&2; }
+print_error() { printf "%b%bERROR:%b %s%b\n" "$bold" "$red" "$nc" "$1" "$reset" >&2; }
 
 print_version()
 {
@@ -694,7 +695,7 @@ traverse_json_file()
 
 		for key in "${!supported_distros[@]}"; do
 			if [[ "${supported_distros[$key]}" == "$distro" ]]; then
-				print_msg "${bold}${und}$key"
+				print_msg "${und}$key"
 				break
 			fi
 		done
@@ -727,7 +728,7 @@ main_menu()
 
 	clear -x
 
-	print_msg "${bold}${und}Main Menu"
+	print_msg "${und}Main Menu"
 
 	select main_menu_choice in "${sorted_distros[@]}"; do
 		if [[ -z "$main_menu_choice" ]]; then
