Refactored to use .json config file.
- I feel moving to a .json config file will ease issues with more complex distros. More info about where the file is read from can be found in the "Non AUR Install" section of the README.md.
- New dependency required `jq`.

diff --git a/dl-distro b/dl-distro
--- a/dl-distro
+++ b/dl-distro
@@ -1,89 +1,25 @@
 #!/usr/bin/env bash
+# https://codeberg.org/codeberge/dl-distro/src/branch/master/README.md
+
 set -euo pipefail
 
-arch_version="2023.08.01"
-debian_version="12.1.0"
-kali_version="2023.3"
-mint_version="21.2"
-mint_de_version="5"
-ubuntu_versions=("23.04" "22.04.3")
-
-# ARCH
-get_arch_variables() {
-    gpg_key="0x3E80CA1A8B89F69CBA57D98A76A5EF9054449A5C" # https://archlinux.org/download
-    url="https://geo.mirror.pkgbuild.com/iso/${arch_version}"
-    iso_file="archlinux-${arch_version}-x86_64.iso"
-    sig_file="archlinux-${arch_version}-x86_64.iso.sig"
-    sum_file="b2sums.txt"
-    sum_algo="b2sum"
-}
-
-# DEBIAN
-get_debian_variables() {
-    gpg_key="DF9B9C49EAA9298432589D76DA87E80D6294BE9B" # https://www.debian.org/CD/verify
-    url="https://cdimage.debian.org/debian-cd/current/${architecture}/iso-cd"
-    iso_file="debian-${debian_version}-${architecture}-netinst.iso"
-    live_url="https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid"
-    live_iso_file="debian-live-${debian_version}-amd64-${desktop_env}.iso"
-    sig_file="SHA512SUMS.sign"
-    sum_file="SHA512SUMS"
-    sum_algo="sha512sum"
-}
-
-# KALI
-get_kali_variables() {
-    gpg_key="44C6513A8E4FB3D30875F758ED444FF07D8D0BF6" # https://www.kali.org/docs/introduction/download-images-securely
-    url="https://cdimage.kali.org/kali-${kali_version}"
-    weekly_url="https://cdimage.kali.org/${kali_version}"
-    iso_file="kali-linux-${kali_file_version}-${image_type}-${architecture}.${ext}"
-    weekly_iso_file="kali-linux-$(date +%Y)-${weekly_version}-${image_type}-${architecture}.${ext}"
-    sig_file="SHA256SUMS.gpg"
-    sum_file="SHA256SUMS"
-    sum_algo="sha256sum"
-}
-
-# MINT
-get_mint_variables() {
-    gpg_key="27DEB15644C6B3CF3BD7D291300F846BA25BAE09" # https://linuxmint.com/verify.php
-    url="https://mirrors.layeronline.com/linuxmint/stable/${mint_version}"
-    iso_file="linuxmint-${mint_version}-${desktop_env}-64bit.iso"
-    de_url="https://mirrors.layeronline.com/linuxmint/debian"
-    de_iso_file="lmde-${mint_de_version}-cinnamon-64bit.iso"
-    sig_file="sha256sum.txt.gpg"
-    sum_file="sha256sum.txt"
-    sum_algo="sha256sum"
-}
-
-# UBUNTU
-get_ubuntu_variables() {
-    gpg_key="843938DF228D22F7B3742BC0D94AA3F0EFE21092" # https://ubuntu.com/tutorials/how-to-verify-ubuntu
-    url="https://releases.ubuntu.com/${ubuntu_version}"
-    iso_file="ubuntu-${ubuntu_version}-${image_type}-amd64.iso"
-    sig_file="SHA256SUMS.gpg"
-    sum_file="SHA256SUMS"
-    sum_algo="sha256sum"
-}
-
 download_and_verify_iso() {
-    # Check if ISO exists and exit. Used with an expect script to check every ISO combination
+
     if [[ "$download_path" == "--spider" ]]; then
         if ! wget -nv -c --spider "$url/$iso_file"; then
             echo -e "\nFailed to download $iso_file.\n"
             exit 1
 	else
-	    exit 0
+            exit 0
         fi
     fi
 
-    # Make directory if not $pwd and cd into it
     if [[ "$download_path" != "$(pwd)" ]]; then
         mkdir -p "$download_path" || { echo "Failed to create directory $download_path"; exit 1; }
         cd "$download_path" || { echo "Failed to change directory to $download_path"; exit 1; }
     fi
 
-    # Check if key already exists
     if ! gpg --list-keys "$gpg_key" &> /dev/null; then
-	# Import if it does not exist
         echo -e "Fetching GPG key: $gpg_key\n"
         if ! gpg --keyserver keyserver.ubuntu.com --recv-keys "$gpg_key"; then
             echo -e "\nError: Failed to fetch GPG key $gpg_key.\n"
@@ -91,7 +27,6 @@ download_and_verify_iso() {
         fi
     fi
 
-    # Get the sig and sum file or all files if Arch
     if [[ "$distro" != "arch" ]]; then
         for file in "$sig_file" "$sum_file"; do
             if ! wget -q --show-progress -c "$url/$file"; then
@@ -108,22 +43,20 @@ download_and_verify_iso() {
         done
     fi
 
-    # Verify the the GPG signature, Arch is sig>iso not sig>sum
     if [[ "$distro" != "arch" ]]; then
         if ! gpg --verify "$sig_file" "$sum_file"; then
             echo -e "\nGPG verification failed.\n"
-	    rm -f "$sig_file" "$sum_file"
+            rm -f "$sig_file" "$sum_file"
             exit 1
         fi
     else
         if ! gpg --verify "$sig_file" "$iso_file"; then
             echo -e "\nGPG verification failed.\n"
-	    rm -f "$iso_file" "$sig_file" "$sum_file"
-	    exit 1
+            rm -f "$iso_file" "$sig_file" "$sum_file"
+            exit 1
         fi
     fi
 
-    # Get the ISO if not Arch
     if [[ "$distro" != "arch" ]]; then
         if ! wget -q --show-progress -c "$url/$iso_file"; then
             echo -e "\nFailed to download $iso_file.\n"
@@ -131,179 +64,199 @@ download_and_verify_iso() {
         fi
     fi
 
-    # Verify shasums
     if ! "$sum_algo" -c --ignore-missing "$sum_file"; then
         echo -e "\n$sum_algo verification failed.\n"
         rm -f "$iso_file" "$sig_file" "$sum_file"
         exit 1
     fi
 
-    # Cleanup
     rm -f "$sig_file" "$sum_file"
     echo -e "\nDownload and verification succeeded.\n"
     exit 0
+
 }
 
-# Takes an array an assigns users choice to a variable.
 get_choice() {
-    variable_name="$1"
-    shift
-    options=("$@")
 
-    # If there's only one option, automatically select it
-    if [[ ${#options[@]} -eq 1 ]]; then
-	declare -g "$variable_name=${options[0]}"
+    local options=("$@")
+    local num_options="${#options[@]}"
+
+    if [[ "$num_options" -eq 1 ]]; then
+        printf "%s" "${options[0]}"
         return
     fi
 
-    # Display the array to the user
-    echo "Available options:"
-    for ((i=0; i<${#options[@]}; i++)); do
-        echo "$((i+1)).) ${options[$i]}"
+    echo >&2
+
+    for i in "${!options[@]}"; do
+        printf "   %d. %s\n" "$((i+1))" "${options[$i]}" >&2
     done
 
-    while :; do
-        read -rp "Enter a number (1-${#options[@]}): " choice
-        if [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 && "$choice" -le "${#options[@]}" ]]; then
-            declare -g "$variable_name=${options[$((choice-1))]}" # Assign chosen option to variable_name
-            echo -e "\nYou chose: ${!variable_name}\n"
-            break
-        else
-            echo -e "\nInvalid choice. Please try again.\n"
-        fi
-    done
+    echo >&2
+
+    read -rp "Enter your choice (1-$num_options): " user_choice >&2
+
+    printf "%s" "${options[$user_choice-1]}"
+
 }
 
 download_arch() {
-    get_arch_variables
+
+    version="$(jq -r ".${distro}.version" "$json_data")"
+    gpg_key="$(jq -r ".${distro}.gpg_key" "$json_data")"
+    url="$(jq -r ".${distro}.url" "$json_data" | sed "s/{version}/$version/")"
+    iso_file="$(jq -r ".${distro}.iso_file" "$json_data" | sed "s/{version}/$version/")"
+    sig_file="$(jq -r ".${distro}.sig_file" "$json_data" | sed "s/{version}/$version/")"
+    sum_file="$(jq -r ".${distro}.sum_file" "$json_data")"
+    sum_algo="$(jq -r ".${distro}.sum_algo" "$json_data")"
+
     download_and_verify_iso
+
 }
 
 download_debian() {
-    supported_images=("Debian" "Debian Live")
-    supported_architectures=("amd64" "arm64" "armel" "armhf" "i386" "mips64el" "mipsel" "ppc64el" "s390x")
-    supported_envs=("cinnamon" "gnome" "kde" "lxde" "lxqt" "mate" "standard" "xfce")
-    architecture=""
-    desktop_env=""
 
-    get_choice image_type "${supported_images[@]}"
+    version="$(jq -r ".${distro}.version" "$json_data")"
+    gpg_key="$(jq -r ".${distro}.gpg_key" "$json_data")"
+    sig_file="$(jq -r ".${distro}.sig_file" "$json_data")"
+    sum_file="$(jq -r ".${distro}.sum_file" "$json_data")"
+    sum_algo="$(jq -r ".${distro}.sum_algo" "$json_data")"
+    installer_type="$(get_choice "Net Installer" "Live Installer")"
 
-    if [[ "$image_type" == "Debian" ]]; then
-        get_choice architecture "${supported_architectures[@]}"
-    else
-        get_choice desktop_env "${supported_envs[@]}"
-    fi
+    case "$installer_type" in
+        "Net Installer")
 
-    get_debian_variables
+            selected_architecture="$(get_choice "amd64" "arm64" "armel" "armhf" "i386" "mips64el" "mipsel" "ppc64el" "s390x")"
+            url="$(jq -r ".${distro}.net_installer.url" "$json_data" | sed "s/{selected_architecture}/$selected_architecture/")"
+            iso_file="$(jq -r ".${distro}.net_installer.iso_file" "$json_data" | sed "s/{version}/$version/" | sed "s/{selected_architecture}/$selected_architecture/")" ;;
 
-    if [[ "$image_type" == "Debian Live" ]]; then
-        url="$live_url"
-	iso_file="$live_iso_file"
-    fi
+        "Live Installer")
+
+            selected_environment="$(get_choice "cinnamon" "gnome" "kde" "lxde" "lxqt" "mate" "standard" "xfce")"
+            url="$(jq -r ".${distro}.live_installer.url" "$json_data")"
+            iso_file="$(jq -r ".${distro}.live_installer.iso_file" "$json_data" | sed "s/{version}/$version/" | sed "s/{selected_environment}/$selected_environment/")" ;;
+    esac
 
     download_and_verify_iso
+
 }
 
 download_kali() {
-    supported_versions=("$kali_version" "kali-weekly")
-    supported_images=("live" "qemu" "virtualbox" "vmware" "hyperv" "installer" "installer-netinst" "installer-purple")
-    kali_file_version=""
-    weekly_version=""
 
-    get_choice kali_version "${supported_versions[@]}"
-    get_choice image_type "${supported_images[@]}"
+    version="$(jq -r ".${distro}.version" "$json_data")"
+    gpg_key="$(jq -r ".${distro}.gpg_key" "$json_data")"
+    sig_file="$(jq -r ".${distro}.sig_file" "$json_data")"
+    sum_file="$(jq -r ".${distro}.sum_file" "$json_data")"
+    sum_algo="$(jq -r ".${distro}.sum_algo" "$json_data")"
+    installer_type="$(get_choice "Kali" "Kali (weekly)")"
+    selected_image="$(get_choice "live" "qemu" "virtualbox" "vmware" "hyperv" "installer" "installer-netinst" "installer-purple")"
 
-    # Assign specific architectures and file extensions based off of users choice for image_type and version
-    case "$image_type" in
-    "live"|"installer"|"installer-netinst") supported_architectures=("amd64" "arm64" "i386"); ext="iso" ;;
-    "installer-purple") supported_architectures=("amd64"); ext="iso" ;;
-    "hyperv") supported_architectures=("amd64"); ext="7z" ;;
-    *)
-        if [[ "$kali_version" == "kali-weekly" ]]; then
-            supported_architectures=("amd64");
-        else
-            supported_architectures=("amd64" "i386");
-        fi
-        ext="7z"
-        ;;
+    case "$selected_image" in
+        "live"|"installer"|"installer-netinst") selected_architecture="$(get_choice "amd64" "arm64" "i386")"; ext="iso" ;;
+        "installer-purple")                     selected_architecture="$(get_choice "amd64")";                ext="iso" ;;
+        "hyperv")                               selected_architecture="$(get_choice "amd64")";                ext="7z" ;;
+        *)
+           if [[ "$installer_type" == "Kali (weekly)" ]]; then
+               selected_architecture="$(get_choice "amd64")"
+           else
+               selected_architecture="$(get_choice "amd64" "i386")"
+           fi
+           ext="7z" ;;
     esac
 
-    get_choice architecture "${supported_architectures[@]}"
+    if [[ "$installer_type" != "Kali (weekly)" ]]; then
 
-    if [[ "$kali_version" != "kali-weekly" ]]; then
-        # Array to patch the filename from 2023.x to 2023.xa. Comment out when no patch exists
         declare -A type_to_patch
         #type_to_patch=( ["hyperv"]="a" ["installer"]="a" ["installer-netinst"]="a" ["installer-purple"]="a" )
 
-        # Prepare kali_file_version with kali_version before checking for a patch
-        kali_file_version="${kali_version}"
+        file_version="$version"
 
-        # If the type_to_patch array is populated, use it to patch the filename_version
-        if [[ -v type_to_patch["$image_type"] ]]; then
-            patch="${type_to_patch[$image_type]}"
-            if [[ -n $patch ]]; then  # If this image_type has a patch
-                kali_file_version+="$patch"  # Append the patch to the filename version
+        if [[ -v type_to_patch["$selected_image"] ]]; then
+
+            patch="${type_to_patch[$selected_image]}"
+
+            if [[ -n "$patch" ]]; then
+                file_version+="$patch"
             fi
         fi
     fi
 
-    # Get kali-weekly version
-    if [[ "$kali_version" == "kali-weekly" ]]; then
-        html_content="$(wget -qO- https://cdimage.kali.org/kali-weekly/)"
-        weekly_version="$(echo "$html_content" | grep -o 'W[0-9]\+' | sort -r | head -n1)"
-    fi
+    if [[ "$installer_type" == "Kali (weekly)" ]]; then
 
-    get_kali_variables
+        url="$(jq -r ".${distro}.weekly.url" "$json_data")"
+        html_content="$(wget -qO- "$url")"
+        current_week_num="$(echo "$html_content" | grep -o 'W[0-9]\+' | sort -r | head -n1 | cut -c2-)"
+        iso_file="$(jq -r ".${distro}.weekly.iso_file" "$json_data" | sed "s/{current_week_num}/$current_week_num/" | sed "s/{selected_image}/$selected_image/" | sed "s/{selected_architecture}/$selected_architecture/" | sed "s/{ext}/$ext/")"
 
-    # Check if the current week's ISO file exists, fallback to previous week
-    if [[ "$kali_version" == "kali-weekly" ]]; then
-        url="$weekly_url"
-        iso_file="$weekly_iso_file"
         if ! echo "$html_content" | grep -q "$iso_file"; then
-            echo -e "No new ISO for week: $weekly_version. Downloading previous week.\n"
-            week_num="${weekly_version#W}"
-            (( prev_week_num=week_num-1 ))
-            weekly_version="W${prev_week_num}"
+
+            echo -e "No new ISO for week: $current_week_num. Downloading previous week.\n"
+            (( prev_week_num=current_week_num-1 ))
+            iso_file="${iso_file//$current_week_num/$prev_week_num}"
+
         fi
+
+    else
+
+        url="$(jq -r ".${distro}.standard.url" "$json_data")"
+        iso_file="$(jq -r ".${distro}.standard.iso_file" "$json_data" | sed "s/{file_version}/$file_version/" | sed "s/{selected_image}/$selected_image/" | sed "s/{selected_architecture}/$selected_architecture/" | sed "s/{ext}/$ext/")"
+
     fi
 
     download_and_verify_iso
+
 }
 
 download_mint() {
-    supported_images=("Mint" "Debian Edition")
-    supported_envs=("cinnamon" "mate" "xfce")
-    desktop_env=""
 
-    get_choice image_type "${supported_images[@]}"
+    gpg_key="$(jq -r ".${distro}.gpg_key" "$json_data")"
+    sig_file="$(jq -r ".${distro}.sig_file" "$json_data")"
+    sum_file="$(jq -r ".${distro}.sum_file" "$json_data")"
+    sum_algo="$(jq -r ".${distro}.sum_algo" "$json_data")"
+    installer_type="$(get_choice "Mint" "Mint (Debian Edition)")"
 
-    if [[ "$image_type" == "Mint" ]]; then
-        get_choice desktop_env "${supported_envs[@]}"
-    fi
+    if [[ "$installer_type" == "Mint" ]]; then
 
-    get_mint_variables
+        selected_environment="$(get_choice "cinnamon" "mate" "xfce")"
+        version="$(jq -r ".${distro}.standard.version" "$json_data")"
+        url="$(jq -r ".${distro}.standard.url" "$json_data" | sed "s/{version}/$version/")"
+        iso_file="$(jq -r ".${distro}.standard.iso_file" "$json_data" | sed "s/{version}/$version/" | sed "s/{selected_environment}/$selected_environment/")"
 
-    if [[ "$image_type" == "Debian Edition" ]]; then
-        url="$de_url"
-	iso_file="$de_iso_file"
+    else
+
+       version="$(jq -r ".${distro}.debian_edition.version" "$json_data")"
+       url="$(jq -r ".${distro}.debian_edition.url" "$json_data")"
+       iso_file="$(jq -r ".${distro}.debian_edition.iso_file" "$json_data" | sed "s/{version}/$version/")"
+
     fi
 
     download_and_verify_iso
+
 }
 
 download_ubuntu() {
-    supported_images=("desktop" "live-server")
-    ubuntu_version=""
-    image_type=""
 
-    get_choice ubuntu_version "${ubuntu_versions[@]}"
-    get_choice image_type "${supported_images[@]}"
-    get_ubuntu_variables
+    gpg_key="$(jq -r ".${distro}.gpg_key" "$json_data")"
+    sig_file="$(jq -r ".${distro}.sig_file" "$json_data")"
+    sum_file="$(jq -r ".${distro}.sum_file" "$json_data")"
+    sum_algo="$(jq -r ".${distro}.sum_algo" "$json_data")"
+    installer_type="$(get_choice "Ubuntu" "Ubuntu (LTS)")"
+
+    if [[ "$installer_type" == "Ubuntu" ]]; then
+        version="$(jq -r ".${distro}.standard.version" "$json_data")"
+    else
+        version="$(jq -r ".${distro}.lts.version" "$json_data")"
+    fi
+
+    selected_image="$(get_choice "desktop" "live-server")"
+    url="$(jq -r ".${distro}.url" "$json_data" | sed "s/{version}/$version/")"
+    iso_file="$(jq -r ".${distro}.iso_file" "$json_data" | sed "s/{version}/$version/" | sed "s/{selected_image}/$selected_image/")"
+
     download_and_verify_iso
-}
 
+}
 check_dependencies() {
-    for cmd in wget gpg; do
+    for cmd in wget gpg jq; do
         if ! command -v "$cmd" &> /dev/null; then
             echo "The following dependency is missing: $cmd"
             echo "Please install it and rerun the script."
@@ -337,16 +290,27 @@ dl_distro() {
     download_path="${2:-$(pwd)}"
 
     if [[ "$distro" == "-h" || "$distro" == "--help" || "$distro" == "help" ]]; then
-	usage
-	exit 0
+        usage
+        exit 0
+    fi
+
+    if [[ -f "$HOME/.config/dl-distro/distro_data.json" ]]; then
+        json_data="$HOME/.config/dl-distro/distro_data.json"
+    elif [[ -f "/usr/share/dl-distro/distro_data.json" ]]; then
+        json_data="/usr/share/dl-distro/distro_data.json"
+    elif [[ -f "$(dirname "$0")/distro_data.json" ]]; then
+        json_data="$(dirname "$0")/distro_data.json"
+    else
+        echo "Error: distro_data.json not found in any of the expected locations."
+        exit 1
     fi
 
     case "$distro" in
         "arch") download_arch ;;
         "debian") download_debian ;;
-	"kali") download_kali ;;
-	"mint") download_mint ;;
-	"ubuntu") download_ubuntu ;;
+        "kali") download_kali ;;
+        "mint") download_mint ;;
+        "ubuntu") download_ubuntu ;;
         *) echo "Error: Please use -h or --help for usage and supported distros."; exit 1 ;;
     esac
 }
